### ISSUE TITLE
Airdrop to EOS accounts / UID interface

### ISSUE THREAD

**Issue by xia256** [Novusphere/discussions-vue#302]

**Comment by xia256** [comment]
Need clarity of how UID is suppose to be integrated.
Does the airdropper input a posting public key or a wallet public key? Do we allow both and just try to detect?

Will omit UID for now and rebuild only with EOS / Telos accounts.

**Comment by bluabaleno** [comment]
It's not the easiest thing for the user to find their posting key, since we don't display it anywhere (as far as I know) but they can access their wallet key via the wallet tab right?

So let's do wallet key. 

You mentioned using display names as well, but that could be tricky since users can change it. Seeing how this will be an internal tool for the forseeable time, I think using wallet key is sufficent
